// ================================================
// ADVOCATE SAATHI — LAWYER DASHBOARD DATA
// lawyer/data.js
// ================================================

const DATA = {

  lawyer: {
    name:      'Adv. Rajesh Sharma',
    initials:  'RS',
    email:     'rajesh@advocatesaathi.com',
    rating:    4.8,
    cases:     47,
    active:    12,
    pending:   8,
    earnings:  '₹1,24,500',
    available: true,
  },

  cases: [
    {
      id:       'C001',
      title:    'Unpaid Salary — TechCorp Pvt Ltd',
      client:   'Priya Sharma',
      clientInitials: 'PS',
      clientColor: '#ef4444',
      type:     'Labour Law',
      category: 'labour',
      status:   'urgent',
      urgency:  'high',
      fir:      true,
      description: 'Employee of TechCorp Pvt Ltd claims 4 months salary totalling ₹1,84,000 is pending. Company has not responded to prior notices or calls. Employee has all salary slips and employment documents.',
      aiSummary: 'High-priority labour case. Payment of Wages Act 1936 & IPC Section 406 applicable. FIR recommended given employer non-response. Strong documentary evidence available. Estimated resolution: 45-60 days via Labour Court.',
      timeline: [
        { title: 'Case received & reviewed', date: 'Mar 15, 2026', status: 'done' },
        { title: 'Legal notice sent to TechCorp', date: 'Mar 18, 2026', status: 'done' },
        { title: 'FIR filing at Labour Cell', date: 'Mar 22, 2026', status: 'active' },
        { title: 'Labour Court hearing', date: 'Apr 5, 2026', status: 'todo' },
        { title: 'Resolution & recovery', date: 'TBD', status: 'todo' },
      ],
      messages: [
        { from: 'client', text: 'Sir, I have joined Advocate Saathi and need help with salary recovery.', time: 'Mar 15, 10:02 AM' },
        { from: 'lawyer', text: 'Hello Priya, I have reviewed your case. You have a strong case under Payment of Wages Act. Please share your salary slips and appointment letter.', time: 'Mar 15, 11:30 AM' },
        { from: 'client', text: 'I have uploaded all salary slips from June to September. Please review.', time: 'Mar 15, 2:15 PM' },
        { from: 'lawyer', text: 'Documents received. I have drafted the legal notice to TechCorp. Will send via registered post today.', time: 'Mar 18, 9:00 AM' },
        { from: 'client', text: 'Thank you sir. Company HR called and said they will respond in 15 days.', time: 'Mar 19, 3:45 PM' },
        { from: 'lawyer', text: 'Good. If they do not respond within the notice period, we will file FIR at the Labour Cell. Keep all communication records.', time: 'Mar 19, 4:00 PM' },
        { from: 'client', text: 'Sir, I have uploaded the salary slips. Please review when possible.', time: 'Mar 20, 9:05 AM' },
      ],
      documents: [
        { name: 'Offer_Letter_TechCorp.pdf', size: '245 KB', type: 'pdf', icon: '📄' },
        { name: 'Salary_Slips_Jun-Sep.pdf',  size: '1.2 MB', type: 'pdf', icon: '📄' },
        { name: 'Legal_Notice_Draft.docx',   size: '58 KB',  type: 'doc', icon: '📝' },
        { name: 'Email_Proof.png',           size: '340 KB', type: 'img', icon: '🖼️' },
      ],
    },
    {
      id:       'C002',
      title:    'UPI Fraud — ₹82,000 Stolen',
      client:   'Amit Kumar',
      clientInitials: 'AK',
      clientColor: '#8b5cf6',
      type:     'Cyber Crime',
      category: 'cyber',
      status:   'urgent',
      urgency:  'high',
      fir:      true,
      description: 'Client lost ₹82,000 via phishing link received on WhatsApp. Transaction happened on March 10. Bank has denied refund claim citing user negligence. Screenshots and transaction IDs available.',
      aiSummary: 'IT Act Sections 66C and 66D applicable along with IPC 420. Bank denial constitutes deficiency of service. Two-track approach recommended: FIR at Cyber Cell + Bank Ombudsman complaint. Strong case for full recovery.',
      timeline: [
        { title: 'Case reviewed & FIR guidance given', date: 'Mar 12, 2026', status: 'done' },
        { title: 'Bank complaint filed', date: 'Mar 14, 2026', status: 'done' },
        { title: 'FIR filed at Cyber Cell', date: 'Mar 17, 2026', status: 'done' },
        { title: 'Bank Ombudsman complaint', date: 'Mar 21, 2026', status: 'active' },
        { title: 'Recovery & resolution', date: 'TBD', status: 'todo' },
      ],
      messages: [
        { from: 'client', text: 'Sir I lost ₹82,000 in a UPI scam. I clicked a link and money was gone.', time: 'Mar 12, 8:30 AM' },
        { from: 'lawyer', text: 'Amit, do not panic. Immediately call 1930 (cyber helpline) and your bank fraud desk. Take screenshots of everything.', time: 'Mar 12, 8:45 AM' },
        { from: 'client', text: 'Done sir. Bank said they will investigate but cannot guarantee refund.', time: 'Mar 12, 11:00 AM' },
        { from: 'lawyer', text: 'That is not acceptable. Bank has an obligation under RBI guidelines. We will file a formal complaint and escalate to Ombudsman if needed.', time: 'Mar 12, 11:30 AM' },
        { from: 'client', text: 'What is the status of my bank complaint?', time: 'Mar 20, 9:22 AM' },
      ],
      documents: [
        { name: 'UPI_Transaction_Screenshot.png', size: '156 KB', type: 'img', icon: '🖼️' },
        { name: 'Bank_Complaint_Receipt.pdf',     size: '89 KB',  type: 'pdf', icon: '📄' },
        { name: 'FIR_Copy_Cyber_Cell.pdf',        size: '120 KB', type: 'pdf', icon: '📄' },
      ],
    },
    {
      id:       'C003',
      title:    'Security Deposit — ₹95,000',
      client:   'Meera Nair',
      clientInitials: 'MN',
      clientColor: '#06b6d4',
      type:     'Property Law',
      category: 'property',
      status:   'active',
      urgency:  'medium',
      fir:      false,
      description: 'Tenant vacated property in Bangalore on January 15. Landlord has not returned security deposit of ₹95,000 despite 60 days passing. Rental agreement available. Property was vacated in good condition.',
      aiSummary: 'Transfer of Property Act 1882 & IPC Section 406 applicable. Legal notice sent and landlord has not responded. Civil court filing recommended. Rental agreement is strong evidence. Case timeline: 60-90 days.',
      timeline: [
        { title: 'Case accepted & documents reviewed', date: 'Mar 5, 2026', status: 'done' },
        { title: 'Legal notice sent via registered post', date: 'Mar 10, 2026', status: 'done' },
        { title: 'Notice reply period ends', date: 'Apr 9, 2026', status: 'active' },
        { title: 'Civil court filing', date: 'Apr 15, 2026', status: 'todo' },
      ],
      messages: [
        { from: 'client', text: 'Sir my landlord is not returning my 95,000 deposit. It has been 2 months now.', time: 'Mar 5, 2:00 PM' },
        { from: 'lawyer', text: 'Meera, this is a clear violation. Please share your rental agreement and vacating proof. We will send a legal notice first.', time: 'Mar 5, 3:30 PM' },
        { from: 'client', text: 'I have sent all documents. When will the notice be sent?', time: 'Mar 8, 10:00 AM' },
        { from: 'lawyer', text: 'Notice has been drafted and will be sent via registered post today. Landlord has 30 days to respond.', time: 'Mar 10, 9:00 AM' },
        { from: 'client', text: 'Thank you for sending the notice. Will wait for response.', time: 'Mar 10, 4:30 PM' },
      ],
      documents: [
        { name: 'Rental_Agreement.pdf',     size: '340 KB', type: 'pdf', icon: '📄' },
        { name: 'Vacating_Photos.zip',      size: '4.2 MB', type: 'zip', icon: '📁' },
        { name: 'Legal_Notice_Sent.pdf',    size: '78 KB',  type: 'pdf', icon: '📄' },
        { name: 'Postal_Receipt.jpg',       size: '95 KB',  type: 'img', icon: '🖼️' },
      ],
    },
    {
      id:       'C004',
      title:    'Consumer Complaint — Defective Laptop',
      client:   'Rahul Singh',
      clientInitials: 'RS',
      clientColor: '#10b981',
      type:     'Consumer Rights',
      category: 'consumer',
      status:   'pending',
      urgency:  'low',
      fir:      false,
      description: 'Client purchased a laptop worth ₹65,000 from Flipkart. Laptop arrived with display damage. Seller refused return claim citing shipping damage policy. Consumer Protection Act 2019 applies.',
      aiSummary: 'Consumer Protection Act 2019 applicable. E-commerce seller cannot refuse return for manufacturing defects within return window. District Consumer Forum filing recommended. Filing fee: ₹200. Expected outcome: Full refund + compensation.',
      timeline: [
        { title: 'Case reviewed', date: 'Feb 28, 2026', status: 'done' },
        { title: 'Consumer forum documents prepared', date: 'Mar 5, 2026', status: 'done' },
        { title: 'Forum filing complete', date: 'Mar 12, 2026', status: 'done' },
        { title: 'Hearing date awaited', date: 'TBD', status: 'active' },
      ],
      messages: [
        { from: 'client', text: 'Sir Flipkart is refusing to take back my laptop which arrived damaged.', time: 'Feb 28, 11:00 AM' },
        { from: 'lawyer', text: 'This is a clear case under CPA 2019. We will file in the District Consumer Forum. Please share your order details and photos.', time: 'Feb 28, 12:30 PM' },
        { from: 'client', text: 'Documents uploaded. Thank you for help.', time: 'Mar 5, 2:00 PM' },
        { from: 'lawyer', text: 'Case has been filed in District Consumer Forum. You will receive the hearing date by post.', time: 'Mar 12, 10:00 AM' },
        { from: 'client', text: 'Okay noted. I\'ll collect the documents tomorrow.', time: 'Mar 19, 3:00 PM' },
      ],
      documents: [
        { name: 'Flipkart_Invoice.pdf',       size: '112 KB', type: 'pdf', icon: '📄' },
        { name: 'Damaged_Laptop_Photos.zip',  size: '8.1 MB', type: 'zip', icon: '📁' },
        { name: 'Forum_Filing_Receipt.pdf',   size: '67 KB',  type: 'pdf', icon: '📄' },
      ],
    },
    {
      id:       'C005',
      title:    'Cheque Bounce — ₹3,50,000',
      client:   'Deepa Verma',
      clientInitials: 'DV',
      clientColor: '#f97316',
      type:     'Civil Law',
      category: 'civil',
      status:   'active',
      urgency:  'high',
      fir:      false,
      description: 'Client issued ₹3,50,000 cheque which was dishonoured due to insufficient funds. NI Act Section 138 case. Cheque drawer is an ex-business partner.',
      aiSummary: 'NI Act Section 138 mandatory notice sent. 15-day payment window active. Strong criminal and civil remedies. Magistrate court complaint recommended if no payment.',
      timeline: [
        { title: 'NI Act notice sent', date: 'Mar 8, 2026', status: 'done' },
        { title: '15-day payment window', date: 'Mar 8 - Mar 23', status: 'active' },
        { title: 'Magistrate court complaint', date: 'Mar 24, 2026', status: 'todo' },
      ],
      messages: [
        { from: 'client', text: 'My business partner gave a cheque of 3.5 lakh which bounced.', time: 'Mar 7, 9:00 AM' },
        { from: 'lawyer', text: 'This is a criminal offence under NI Act 138. I will send the mandatory notice today. He has 15 days to pay or face criminal case.', time: 'Mar 7, 10:00 AM' },
        { from: 'client', text: 'Notice sent. He called and said he will pay by end of week.', time: 'Mar 10, 2:00 PM' },
      ],
      documents: [
        { name: 'Bounced_Cheque_Copy.pdf',  size: '88 KB',  type: 'pdf', icon: '📄' },
        { name: 'Bank_Return_Memo.pdf',     size: '55 KB',  type: 'pdf', icon: '📄' },
        { name: 'NI_Act_Notice.docx',       size: '42 KB',  type: 'doc', icon: '📝' },
      ],
    },
  ],
};
